// GENERATED by scripts/generate-frontend-pages.js — do not edit by hand.
//
// The frontend's mounted App.jsx routes, mirrored so API Performance can list and
// switch pages. Regenerate after adding a route:
//   node scripts/generate-frontend-pages.js
//
// `linked` means a persistent menu points at it. Detail, edit and redirect
// routes may intentionally be unlinked and still be part of a live workflow.

const PAGES = [
  {
    "path": "/",
    "label": "Home",
    "linked": false,
    "locked": true
  },
  {
    "path": "/Attendance-Report",
    "label": "Attendance Report",
    "linked": false,
    "locked": false
  },
  {
    "path": "/Followups",
    "label": "Followups",
    "linked": false,
    "locked": false
  },
  {
    "path": "/SendMessage",
    "label": "Send Message",
    "linked": false,
    "locked": false
  },
  {
    "path": "/WhatsAppBroadcastPage",
    "label": "Whats App Broadcast Page",
    "linked": false,
    "locked": false
  },
  {
    "path": "/WhatsAppHome",
    "label": "WhatsApp Home",
    "linked": true,
    "locked": false
  },
  {
    "path": "/WhatsAppSendPage",
    "label": "Whats App Send Page",
    "linked": false,
    "locked": false
  },
  {
    "path": "/accounts/bank-reconciliation",
    "label": "Bank Reconciliation",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/bank-reconciliation/:uuid",
    "label": "Bank Reconciliation",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/day-book",
    "label": "Day Book",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/day-book/:uuid",
    "label": "Day Book",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/diary-upload",
    "label": "Diary Upload",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/followups",
    "label": "Payment Reminders",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/opening-balance",
    "label": "Opening Balance",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/opening-balance-upload",
    "label": "OB Upload (CSV)",
    "linked": true,
    "locked": false
  },
  {
    "path": "/accounts/payment",
    "label": "Payment",
    "linked": false,
    "locked": false
  },
  {
    "path": "/accounts/receipt",
    "label": "Receipt",
    "linked": false,
    "locked": false
  },
  {
    "path": "/accounts/trial-balance",
    "label": "Trial Balance",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addCustomer",
    "label": "Add Customer",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addCustomergroup",
    "label": "Add Customer Group",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addItem",
    "label": "Add Item",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addItemgroup",
    "label": "Add Item Group",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addOrder",
    "label": "Add Order",
    "linked": false,
    "locked": false
  },
  {
    "path": "/addOrder1",
    "label": "Add Order1",
    "linked": false,
    "locked": false
  },
  {
    "path": "/addPayable",
    "label": "Record Expense",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addPayment",
    "label": "Add Payment",
    "linked": false,
    "locked": false
  },
  {
    "path": "/addPriority",
    "label": "Add Priority",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addRecievable",
    "label": "Record Income",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addTask",
    "label": "Add Task Master",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addTaskgroup",
    "label": "Add Task Group",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addTransaction",
    "label": "Add Transaction",
    "linked": false,
    "locked": false
  },
  {
    "path": "/addTransaction1",
    "label": "Add Transaction1",
    "linked": false,
    "locked": false
  },
  {
    "path": "/addUser",
    "label": "Add User",
    "linked": true,
    "locked": false
  },
  {
    "path": "/addUsergroup",
    "label": "Add User Group",
    "linked": true,
    "locked": false
  },
  {
    "path": "/admin/business-profile",
    "label": "Business Profile",
    "linked": true,
    "locked": false
  },
  {
    "path": "/admin/drive-folder-report",
    "label": "Drive Folder Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/admin/group-permissions",
    "label": "Group Permissions",
    "linked": true,
    "locked": false
  },
  {
    "path": "/admin/user-permissions",
    "label": "User Permissions",
    "linked": true,
    "locked": false
  },
  {
    "path": "/admin/whatsapp-action-log",
    "label": "WhatsApp Action Log",
    "linked": true,
    "locked": false
  },
  {
    "path": "/adminHome",
    "label": "Admin Home",
    "linked": false,
    "locked": false
  },
  {
    "path": "/allBills",
    "label": "Bills Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/allDelivery",
    "label": "All Delivery",
    "linked": false,
    "locked": false
  },
  {
    "path": "/allOrder",
    "label": "All Order",
    "linked": false,
    "locked": false
  },
  {
    "path": "/allOrdersList",
    "label": "All Orders",
    "linked": true,
    "locked": false
  },
  {
    "path": "/allTransaction",
    "label": "All Transaction",
    "linked": false,
    "locked": false
  },
  {
    "path": "/allTransaction1",
    "label": "Transactions 1",
    "linked": true,
    "locked": false
  },
  {
    "path": "/allTransaction2",
    "label": "Transactions 2",
    "linked": true,
    "locked": false
  },
  {
    "path": "/allTransaction3",
    "label": "Customer Ledger",
    "linked": true,
    "locked": false
  },
  {
    "path": "/allTransaction4D",
    "label": "Daily Cash & Bank",
    "linked": true,
    "locked": false
  },
  {
    "path": "/allTransaction5",
    "label": "Transaction Register",
    "linked": true,
    "locked": false
  },
  {
    "path": "/alltransaction2",
    "label": "Alltransaction2",
    "linked": false,
    "locked": false
  },
  {
    "path": "/alltranscation1",
    "label": "Alltranscation1",
    "linked": false,
    "locked": false
  },
  {
    "path": "/attendance",
    "label": "Attendance",
    "linked": true,
    "locked": false
  },
  {
    "path": "/attendance/report",
    "label": "Attendance Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/business-control",
    "label": "Business control",
    "linked": false,
    "locked": false
  },
  {
    "path": "/calllogs",
    "label": "Call Logs",
    "linked": true,
    "locked": false
  },
  {
    "path": "/customerReport",
    "label": "Customer Report",
    "linked": false,
    "locked": false
  },
  {
    "path": "/customers/:id",
    "label": "Customers",
    "linked": false,
    "locked": false
  },
  {
    "path": "/dashboard",
    "label": "Dashboard",
    "linked": false,
    "locked": false
  },
  {
    "path": "/flow-builder",
    "label": "Flow Builder",
    "linked": true,
    "locked": false
  },
  {
    "path": "/gmail/accounts",
    "label": "Accounts",
    "linked": false,
    "locked": false
  },
  {
    "path": "/gmail/compose",
    "label": "Compose",
    "linked": false,
    "locked": false
  },
  {
    "path": "/gmail/history",
    "label": "Email History",
    "linked": true,
    "locked": false
  },
  {
    "path": "/home",
    "label": "Dashboard",
    "linked": true,
    "locked": true
  },
  {
    "path": "/home1",
    "label": "Home1",
    "linked": false,
    "locked": false
  },
  {
    "path": "/invoice/:shareToken",
    "label": "Invoice",
    "linked": false,
    "locked": true
  },
  {
    "path": "/itemReport",
    "label": "Item Report",
    "linked": false,
    "locked": false
  },
  {
    "path": "/login",
    "label": "Login",
    "linked": false,
    "locked": true
  },
  {
    "path": "/operations",
    "label": "Team Operations",
    "linked": true,
    "locked": false
  },
  {
    "path": "/operations/daily-report",
    "label": "Team Daily Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/operations/me",
    "label": "My Operations",
    "linked": true,
    "locked": false
  },
  {
    "path": "/operations/responsibilities",
    "label": "Responsibilities",
    "linked": true,
    "locked": false
  },
  {
    "path": "/operations/settings",
    "label": "Operations Settings",
    "linked": true,
    "locked": false
  },
  {
    "path": "/operations/users/:userUuid",
    "label": "Users",
    "linked": false,
    "locked": false
  },
  {
    "path": "/orderUpdate/:id",
    "label": "Order Update",
    "linked": false,
    "locked": false
  },
  {
    "path": "/orders/board",
    "label": "Board",
    "linked": false,
    "locked": false
  },
  {
    "path": "/orders/new",
    "label": "New",
    "linked": false,
    "locked": false
  },
  {
    "path": "/paymentReport",
    "label": "Payments Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/post-printing",
    "label": "Post printing",
    "linked": false,
    "locked": false
  },
  {
    "path": "/post-printing-jobs",
    "label": "Post-Print Jobs",
    "linked": true,
    "locked": false
  },
  {
    "path": "/priorityReport",
    "label": "Priority Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/purchase-orders",
    "label": "Purchase Orders",
    "linked": true,
    "locked": false
  },
  {
    "path": "/rate-calculator",
    "label": "Rate Calculator",
    "linked": true,
    "locked": false
  },
  {
    "path": "/rate-cards",
    "label": "Rate Card Master",
    "linked": true,
    "locked": false
  },
  {
    "path": "/register",
    "label": "Register",
    "linked": false,
    "locked": true
  },
  {
    "path": "/reports/aging",
    "label": "Aging Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/api-performance",
    "label": "API Performance",
    "linked": true,
    "locked": true
  },
  {
    "path": "/reports/business",
    "label": "Business Reports",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/customers",
    "label": "Customers Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/delivery",
    "label": "Deliveries",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/invoices",
    "label": "Invoices",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/items",
    "label": "Items Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/orders",
    "label": "Orders",
    "linked": false,
    "locked": false
  },
  {
    "path": "/reports/outstanding",
    "label": "Outstanding Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/tasks",
    "label": "Tasks Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/team",
    "label": "Team & Partners Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/transactions",
    "label": "Account Book",
    "linked": true,
    "locked": false
  },
  {
    "path": "/reports/users",
    "label": "Users Report",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social",
    "label": "Overview",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/accounts",
    "label": "Social Accounts",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/analytics",
    "label": "Social Analytics",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/approval",
    "label": "Approval",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/calendar",
    "label": "Calendar",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/create",
    "label": "Create Post",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/create/:id",
    "label": "Create Post",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/library",
    "label": "Content Library",
    "linked": true,
    "locked": false
  },
  {
    "path": "/social/queue",
    "label": "Publishing Queue",
    "linked": true,
    "locked": false
  },
  {
    "path": "/sop",
    "label": "SOP Tasks",
    "linked": true,
    "locked": false
  },
  {
    "path": "/taskReport",
    "label": "Task Report",
    "linked": false,
    "locked": false
  },
  {
    "path": "/tasks/my",
    "label": "My Day",
    "linked": true,
    "locked": false
  },
  {
    "path": "/tasks/new",
    "label": "New",
    "linked": false,
    "locked": false
  },
  {
    "path": "/tasks/pending",
    "label": "Order Tasks",
    "linked": true,
    "locked": false
  },
  {
    "path": "/updateDelivery/:id",
    "label": "Update Delivery",
    "linked": false,
    "locked": false
  },
  {
    "path": "/upi-payment",
    "label": "UPI Payment",
    "linked": true,
    "locked": false
  },
  {
    "path": "/upi/collect/:transactionRef",
    "label": "Collect",
    "linked": false,
    "locked": true
  },
  {
    "path": "/userReport",
    "label": "User Report",
    "linked": false,
    "locked": false
  },
  {
    "path": "/vendorHome",
    "label": "Vendor Home",
    "linked": false,
    "locked": false
  },
  {
    "path": "/vendors",
    "label": "Vendors / Freelancers",
    "linked": true,
    "locked": false
  },
  {
    "path": "/vendors/:id",
    "label": "Vendors / Freelancers",
    "linked": true,
    "locked": false
  },
  {
    "path": "/whatsapp",
    "label": "WhatsApp Cloud",
    "linked": true,
    "locked": false
  },
  {
    "path": "/whatsapp-cloud",
    "label": "Whatsapp cloud",
    "linked": false,
    "locked": false
  },
  {
    "path": "/whatsapp/broadcast",
    "label": "Broadcast Page",
    "linked": true,
    "locked": false
  },
  {
    "path": "/whatsapp/send",
    "label": "Send Message",
    "linked": true,
    "locked": false
  },
  {
    "path": "/workflow-templates",
    "label": "Workflow templates",
    "linked": false,
    "locked": false
  }
];

module.exports = { PAGES };
