export const ROUTES = {
  ROOT: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  HOME: '/home',
  DASHBOARD: '/dashboard',

  ATTENDANCE: '/attendance',
  ATTENDANCE_REPORT: '/attendance/report',
  ATTENDANCE_REPORT_OLD: '/Attendance-Report',

  TASKS: '/tasks',
  MY_TASKS: '/tasks/my',
  TASKS_NEW: '/tasks/new',
  PENDING_TASKS: '/tasks/pending',

  ADD_CUSTOMER: '/addCustomer',
  ADD_CUSTOMER_GROUP: '/addCustomergroup',
  ADD_ITEM: '/addItem',
  ADD_ITEM_GROUP: '/addItemgroup',
  ADD_TASK: '/addTask',
  ADD_TASK_GROUP: '/addTaskgroup',
  ADD_PRIORITY: '/addPriority',
  ADD_USER: '/addUser',
  ADD_USER_GROUP: '/addUsergroup',

  ORDERS_NEW: '/orders/new',
  ORDERS_BOARD: '/orders/board',
  BUSINESS_CONTROL: '/business-control',
  POST_PRINTING_CONTROL: '/post-printing',
  WORKFLOW_TEMPLATES: '/workflow-templates',
  ORDER_KANBAN: '/orders/board',
  ORDER_UPDATE: '/orders/:id/update',
  DELIVERY_UPDATE: '/delivery/update/:id',
  CUSTOMER_360: '/customers/:id',

  RECEIPT: '/accounts/receipt',
  PAYMENT: '/accounts/payment',
  UPI_COLLECT_PUBLIC: '/upi/collect/:transactionRef',
  UPI_PAYMENT: '/upi-payment',
  ADD_PAYMENT: '/addPayment',
  TRIAL_BALANCE: '/accounts/trial-balance',
  FOLLOWUPS: '/accounts/followups',
  ADD_PAYABLE: '/addPayable',
  ADD_RECEIVABLE: '/addRecievable',

  VENDORS: '/vendors',
  VENDOR_DETAILS: '/vendors/:id',

  WHATSAPP: '/whatsapp',
  WHATSAPP_CLOUD: '/whatsapp',
  WHATSAPP_SEND: '/whatsapp/send',
  WHATSAPP_BULK: '/whatsapp/bulk',
  WHATSAPP_LEGACY_HOME: '/WhatsAppHome',
  WHATSAPP_LOGIN_PAGE: '/WhatsAppLogin',
  WHATSAPP_SESSION_PAGE: '/WhatsAppSession',
  WHATSAPP_ADMIN_PANEL: '/WhatsAppAdminPanel',
  WHATSAPP_BROADCAST: '/whatsapp/broadcast',

  REPORTS_ORDERS: '/reports/orders',
  REPORTS_TRANSACTIONS: '/reports/transactions',
  REPORTS_TRANSACTION_1: '/allTransaction1',
  REPORTS_TRANSACTION_2: '/allTransaction2',
  REPORTS_TRANSACTION_3: '/allTransaction3',
  REPORTS_TRANSACTION_4D: '/allTransaction4D',
  REPORTS_CUSTOMERS: '/reports/customers',
  REPORTS_PAYMENTS: '/reports/payments',
  REPORTS_ITEMS: '/reports/items',
  REPORTS_TASKS: '/reports/tasks',
  REPORTS_USERS: '/reports/users',
  REPORTS_VENDORS: '/reports/vendors',
  REPORTS_DELIVERY: '/reports/delivery',
  REPORTS_BILLS: '/allBills',
  REPORTS_PRIORITY: '/priorityReport',
  AGING_REPORT: '/reports/aging',
  PURCHASE_ORDERS: '/purchase-orders',
  POST_PRINTING_JOBS: '/post-printing-jobs',

  DIARY_UPLOAD:        '/accounts/diary-upload',
  DAY_BOOK:            '/accounts/day-book',
  BANK_RECONCILIATION: '/accounts/bank-reconciliation',
  OPENING_BALANCE:     '/accounts/opening-balance',

  // Gmail / Email
  GMAIL_ACCOUNTS: '/gmail/accounts',
  EMAIL_COMPOSE:  '/gmail/compose',
  EMAIL_HISTORY:  '/gmail/history',

  // legacy aliases still used in old code
  ADD_ORDER: '/addOrder',
  ADD_ORDER_V2: '/addOrder1',
  ALL_BILLS: '/allBills',
  ALL_TRANSACTION: '/allTransaction',
  ALL_TRANSACTION_1: '/allTransaction1',
  ALL_TRANSACTION_2: '/allTransaction2',
  ALL_TRANSACTION_3: '/allTransaction3',
  ALL_TRANSACTION_4D: '/allTransaction4D',
  PAYMENT_REPORT: '/paymentReport',
  PRIORITY_REPORT: '/priorityReport',
  CALL_LOGS: '/calllogs',
  FLOW_BUILDER: '/flow-builder',

  // Admin
  ADMIN_USER_PERMISSIONS: '/admin/user-permissions',
};

export const ROUTE_ALIASES = {
  HOME_ADMIN: '/adminHome',
  HOME_VENDOR: '/vendorHome',
  HOME_OLD: '/home1',
  ADD_ORDER_V2_LOWER: '/addorder1',
  PENDING_TASK_LOWER: '/pendingtask',
  ATTENDANCE_REPORT_MIXED: '/Attendance-Report',
  ADD_PAYABLE_TYPO: '/addPayble',
  ALL_TRANSACTION_1_TYPO: '/alltranscation1',
  ALL_TRANSACTION_2_LOWER: '/alltransaction2',
  WHATSAPP_LOGIN: '/WhatsAppLogin',
  WHATSAPP_SESSION: '/WhatsAppSession',
  WHATSAPP_ADMIN: '/WhatsAppAdminPanel',
  WHATSAPP_HOME: '/WhatsAppHome',
  WHATSAPP_BROADCAST_PAGE: '/WhatsAppBroadcastPage',
  WHATSAPP_SEND_PAGE: '/WhatsAppSendPage',
  FOLLOWUPS_OLD: '/Followups',
};
